---
# comment
jobs:

  - name: develop
    plan:
      - get:        secrets
      - get:        repo
        resource:   repo-develop
        trigger:    true
      - task:       build
        file:       repo/tasks/build.yml
      - task:       promote
        file:       repo/tasks/promote.yml
        params:
          tag:      develop

  - name: staging
    plan:
      - get:        secrets
      - get:        repo
        resource:   repo-staging
        trigger:    true
      - task:       build
        file:       repo/tasks/build.yml
      - task:       promote
        file:       repo/tasks/promote.yml
        params:
          tag:      staging

  - name: production
    plan:
      - get:        secrets
      - get:        repo
        resource:   repo-production
        trigger:    true
      - task:       build
        file:       repo/tasks/build.yml
      - task:       promote
        file:       repo/tasks/promote.yml
        params:
          tag:      production

resources:

  - name: repo-develop
    type: git
    source:
      uri:          git@github.com:coreyti/tmp.git
      branch:       master
      private_key:  {{private_key__code}}

  - name: repo-staging
    type: git
    source:
      uri:          git@github.com:coreyti/tmp.git
      branch:       master
      tag_filter:   develop
      ignore_paths: ['CHANGELOG.txt']
      private_key:  {{private_key__code}}

  - name: repo-production
    type: git
    source:
      uri:          git@github.com:coreyti/tmp.git
      branch:       master
      tag_filter:   staging
      ignore_paths: ['CHANGELOG.txt']
      private_key:  {{private_key__code}}

  - name: secrets
    type: git
    source:
      uri:          git@github.com:coreyti/tmp.keys.git
      branch:       master
      private_key:  {{private_key__self}}
