#!/usr/bin/env ruby

now = Time.now
mod = now.to_i % 2

File.open('README.md', 'a') do |file|
  file.puts "Edited at #{now}"
end

if mod == 0
  puts "success"
else
  raise "failure (will be)"
end


# 98b3774
